export const ON_CHANGE_INPUT = 'onChangeInput'
export const ADD_TODO_ITEM = 'addTodoItem'
export const DELETE_TODO_ITEM = 'deleteTodoItem'
export const SET_TODO_LIST = 'setTodoList'
export const GET_TODO_LIST = 'getTodoList'